name: pretty-quick GitHub Action
description: Automatically runs pretty-quick on all your changes.
author: CTcue <ctcue-dev-teams@iqvia.com>

inputs:
  prettier_version:
    description: Specific version of prettier (by default, use the latest version)
    required: false
    default: false
  pretty_quick_version:
    description: Specific version of pretty-quick (by default, use the latest version)
    required: false
    default: false
  pretty_quick_options:
    description: Options for the `pretty-quick` command
    required: false
    default: ""
  root:
    description: Specific the root from where pretty-quick is run
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "award"
  color: "green"
